#!/bin/sh



# postinst script for webpy-example
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

# source debconf library
. /usr/share/debconf/confmodule

case "$1" in

    configure)
        [ -e /etc/systemd/user/default.target.wants/ ] || mkdir -p /etc/systemd/user/default.target.wants/
        ln -sf /usr/lib/systemd/user/cups-fuse.service /etc/systemd/user/default.target.wants/cups-fuse.service
        # restart systemd-user for all users to reread the printer-configuration
        #    echo "postinstall-script for fuse-cups"
        loginctl --no-legend -o cat|awk '{print $2,$3}'|sort|uniq|while read i u ; do
            #echo "restart user-systemd for $u $i"
            if /bin/systemctl is-active "user@${i}.service" >/dev/null ; then
                sudo -u $u /bin/systemctl --user restart cups-fuse.service
            fi
            #sleep 0.5
            #systemctl |grep "user@{$i}.service"  && echo systemctl restart "user@{$i}.service"
        done
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        exit 0
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;

esac

db_stop

exit 0
